"""Criando Tabelas Iniciais

Revision ID: e3a709d28263
Revises: 
Create Date: 2025-03-18 12:29:33.368100

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'e3a709d28263'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('exercicio',
    sa.Column('IdExercicio', sa.Integer(), nullable=False),
    sa.Column('NomeExercicio', sa.String(length=100), nullable=False),
    sa.Column('Grupamento', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('IdExercicio')
    )
    op.create_table('usuario',
    sa.Column('IdUsuario', sa.Integer(), nullable=False),
    sa.Column('Email', sa.String(length=120), nullable=False),
    sa.Column('Senha', sa.String(length=200), nullable=False),
    sa.Column('NomeUsuario', sa.String(length=80), nullable=False),
    sa.Column('EstiloTreino', sa.Integer(), nullable=True),
    sa.Column('DiasAtivos', postgresql.ARRAY(sa.String(length=10)), nullable=True),
    sa.PrimaryKeyConstraint('IdUsuario'),
    sa.UniqueConstraint('Email')
    )
    op.create_table('treino',
    sa.Column('IdTreino', sa.Integer(), nullable=False),
    sa.Column('NomeTreino', sa.String(length=100), nullable=False),
    sa.Column('IdUsuario', sa.Integer(), nullable=False),
    sa.Column('IdExercicios', postgresql.ARRAY(sa.Integer()), nullable=True),
    sa.Column('DiaSemana', sa.String(length=10), nullable=True),
    sa.ForeignKeyConstraint(['IdUsuario'], ['usuario.IdUsuario'], ),
    sa.PrimaryKeyConstraint('IdTreino')
    )
    op.create_table('diatreino',
    sa.Column('IdDiaTreino', sa.Integer(), nullable=False),
    sa.Column('IdTreino', sa.Integer(), nullable=False),
    sa.Column('IdUsuario', sa.Integer(), nullable=False),
    sa.Column('DataTreino', sa.Date(), nullable=False),
    sa.ForeignKeyConstraint(['IdTreino'], ['treino.IdTreino'], ),
    sa.ForeignKeyConstraint(['IdUsuario'], ['usuario.IdUsuario'], ),
    sa.PrimaryKeyConstraint('IdDiaTreino')
    )
    op.create_table('exerciciotreino',
    sa.Column('IdExercicioTreino', sa.Integer(), nullable=False),
    sa.Column('IdExercicio', sa.Integer(), nullable=False),
    sa.Column('IdDiaTreino', sa.Integer(), nullable=False),
    sa.Column('Cargas', postgresql.ARRAY(sa.Integer()), nullable=True),
    sa.Column('Repeticoes', postgresql.ARRAY(sa.Integer()), nullable=True),
    sa.ForeignKeyConstraint(['IdDiaTreino'], ['diatreino.IdDiaTreino'], ),
    sa.ForeignKeyConstraint(['IdExercicio'], ['exercicio.IdExercicio'], ),
    sa.PrimaryKeyConstraint('IdExercicioTreino')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('exerciciotreino')
    op.drop_table('diatreino')
    op.drop_table('treino')
    op.drop_table('usuario')
    op.drop_table('exercicio')
    # ### end Alembic commands ###
